# Site settings
title: Laboratorio Computacional de Ciencia Ciudadana
email: lc3@inmegen.gob.mx
description: > # this means to ignore newlines until "baseurl:"
  El LC3 del INMEGEN busca reunir científicos profesionales con ciudadanos entusiastas 
  para colaborar en el desarrollo de proyectos de análisis de datos y visualización en torno a
  temas de Salud y Medicina Genómica en México.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lc3-inmegen.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  LC3-INMEGEN

# Build settings
markdown: kramdown
